services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gozic-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      
  postgres_product:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: product_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_product_data:/var/lib/postgresql/data    
    networks:
      - gozic-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d product_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      
  auth-service:
    build: 
      context: ./auth-service
      dockerfile: Dockerfile
    volumes:
      - ./auth-service:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DB_HOST=postgres
      - DB_NAME=auth_db
      - DB_USER=postgres
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=5432
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - gozic-network

  product-service:
    build:
      context: ./product_service
      dockerfile: Dockerfile
    volumes:
      - ./product_service:/app
    ports:
      - "8001:8000"
    environment:
      - DEBUG=1
      - DB_HOST=postgres_product
      - DB_NAME=product_db
      - DB_USER=postgres
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=5432
    depends_on:
      postgres_product:
        condition: service_healthy
    networks:
      - gozic-network

volumes:
  postgres_data:
  postgres_product_data:

networks:
  gozic-network:
    driver: bridge