# Generated by Django 5.1.2 on 2025-06-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
