# Generated by Django 5.1.2 on 2025-06-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_variant_sku'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variant',
            options={},
        ),
        migrations.AlterField(
            model_name='variant',
            name='volume',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='variant',
            unique_together={('product', 'volume')},
        ),
    ]
