# Generated by Django 5.1.2 on 2025-06-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_invoice_customer_alter_invoice_invoice_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='totalPrice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
